[theme]
primaryColor = "#FF7A00"
backgroundColor = "#F7FAFC"
secondaryBackgroundColor = "#EEF8F5"
textColor = "#102F3B"
font = "sans serif"

[server]
maxUploadSize = 200

[browser]
gatherUsageStats = false
